Starting R run: 2025-08-16_12-26-34_run-3834
GitHub SHA: f5713f656151c6bd291bc19871d03652ff704759
Triggered by: schedule
-----------------------------------
preparation[1] "LC_CTYPE=it_IT.UTF-8;LC_NUMERIC=C;LC_TIME=it_IT.UTF-8;LC_COLLATE=it_IT.UTF-8;LC_MONETARY=it_IT.UTF-8;LC_MESSAGES=it_IT.UTF-8;LC_PAPER=it_IT.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=it_IT.UTF-8;LC_IDENTIFICATION=C"
Linking to ImageMagick 6.9.12.98
Enabled features: fontconfig, freetype, fftw, heic, lcms, pango, raw, webp, x11
Disabled features: cairo, ghostscript, rsvg
Using 4 threads

Caricamento pacchetto: ‘dplyr’

I seguenti oggetti sono mascherati da ‘package:stats’:

    filter, lag

I seguenti oggetti sono mascherati da ‘package:base’:

    intersect, setdiff, setequal, union


Caricamento pacchetto: ‘lubridate’

I seguenti oggetti sono mascherati da ‘package:base’:

    date, intersect, setdiff, union

[1] "rifiuti"
[1] "calendario"
Errore in file(con, "r") : 
  non è possibile aprire la connessione a 'https://calendar.google.com/calendar/ical/qblk3l3l4vu78epu50r1k3jmj0%40group.calendar.google.com/private-8840cef28a58be04ca66077c9e190c6c/basic.ics'
Chiamate: %>% ... get_calendars -> lapply -> FUN -> ic_read -> readLines -> file
In aggiunta: Messaggio di avvertimento:
In file(con, "r") :
  URL 'https://calendar.google.com/calendar/ical/qblk3l3l4vu78epu50r1k3jmj0%40group.calendar.google.com/private-8840cef28a58be04ca66077c9e190c6c/basic.ics': Timeout di 60 secondi raggiunto
Esecuzione interrotta
